local_repository(
    name = "stage2",
    path = "/home/jean/Documents/learning/Slam_Course/compile_learning/bazel/stage2",
)

bind(
    name = "stage2_",
    actual = "@stage2//main:hello-greet",
)

new_http_archive(
    name = "gtestt",
    url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
    sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
    build_file = "main/gtestt.BUILD",
    strip_prefix = "googletest-release-1.7.0",
)